export {
  createConversation,
  getConversationsByUser,
  getConversation,
  getAdminInbox,
  getMessages,
  postMessage,
  markMessageRead,
  postInternalNote,
  patchAssign,
  patchStatus,
  patchPriority,
  closeConversation,
  unwrapMessageService,
} from './messageServiceApi'
