<script setup>
import { computed } from 'vue'
import {
  AlertTriangle,
  AlignLeft,
  Armchair,
  BadgePercent,
  Banknote,
  BarChart3,
  Bell,
  Bot,
  Box,
  CheckCheck,
  ClipboardList,
  Crown,
  Download,
  FilePlus,
  FileText,
  Flag,
  History,
  Info,
  LayoutDashboard,
  MessageSquare,
  Monitor,
  MoreHorizontal,
  PanelRight,
  Paperclip,
  Pencil,
  Save,
  Smile,
  Tag,
  Tags,
  TrendingUp,
  Users,
  Warehouse,
  Building2,
  CreditCard,
  CalendarDays,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Ban,
  RefreshCw,
  Facebook,
  Gift,
  Heart,
  Handshake,
  House,
  Image,
  ImagePlus,
  Instagram,
  Lock,
  LogOut,
  List,
  Map,
  MapPin,
  Mail,
  MessageCircle,
  MessagesSquare,
  Minus,
  Music2,
  Phone,
  Plus,
  Settings,
  Search,
  Send,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Trash2,
  Truck,
  Video,
  Wallet,
  Clock3,
  Youtube,
  User,
  X,
  Eye,
  EyeOff,
} from 'lucide-vue-next'

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  size: {
    type: Number,
    default: 16,
  },
  strokeWidth: {
    type: Number,
    default: 1.8,
  },
})

const iconMap = {
  alert: AlertTriangle,
  alignLeft: AlignLeft,
  armchair: Armchair,
  bell: Bell,
  bot: Bot,
  chartBar: BarChart3,
  checkCheck: CheckCheck,
  clipboardList: ClipboardList,
  crown: Crown,
  download: Download,
  edit: Pencil,
  filePlus: FilePlus,
  fileText: FileText,
  flag: Flag,
  history: History,
  info: Info,
  layoutDashboard: LayoutDashboard,
  messageSquare: MessageSquare,
  messages: MessagesSquare,
  monitor: Monitor,
  moreHorizontal: MoreHorizontal,
  panelRight: PanelRight,
  paperclip: Paperclip,
  pencil: Pencil,
  save: Save,
  smile: Smile,
  tag: Tag,
  category: Tags,
  trendingUp: TrendingUp,
  users: Users,
  userCircle: User,
  warehouse: Warehouse,
  badgePercent: BadgePercent,
  banknote: Banknote,
  building2: Building2,
  cart: ShoppingCart,
  creditCard: CreditCard,
  calendar: CalendarDays,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  'chevron-left': ChevronLeft,
  chevronRight: ChevronRight,
  'chevron-right': ChevronRight,
  ban: Ban,
  refresh: RefreshCw,
  clock: Clock3,
  clock3: Clock3,
  user: User,
  list: List,
  map: Map,
  mapPin: MapPin,
  lock: Lock,
  mail: Mail,
  messageCircle: MessageCircle,
  messagesSquare: MessagesSquare,
  minus: Minus,
  music2: Music2,
  phone: Phone,
  plus: Plus,
  search: Search,
  send: Send,
  shield: Shield,
  sparkles: Sparkles,
  box: Box,
  camera: Camera,
  heart: Heart,
  handshake: Handshake,
  house: House,
  image: Image,
  'image-plus': ImagePlus,
  eye: Eye,
  eyeOff: EyeOff,
  settings: Settings,
  gift: Gift,
  star: Star,
  store: Store,
  trash: Trash2,
  trash: Trash2,
  truck: Truck,
  video: Video,
  wallet: Wallet,
  cube: Box,
  logout: LogOut,
  close: X,
  x: X,
  check: Check,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
}

const iconComponent = computed(() => iconMap[props.name] ?? User)
</script>

<template>
  <component :is="iconComponent" :size="size" :stroke-width="strokeWidth" aria-hidden="true" />
</template>
