<script setup>
import { computed } from 'vue'
import {
  AlertTriangle,
  AlignLeft,
  ArrowLeft,
  Armchair,
  Axis3d,
  BadgePercent,
  Banknote,
  BarChart3,
  Bed,
  BedDouble,
  Bell,
  Bot,
  Box,
  Boxes,
  Briefcase,
  CheckCheck,
  ClipboardList,
  CloudUpload,
  Crown,
  Download,
  FilePlus,
  FileText,
  Flag,
  Fullscreen,
  Filter,
  Globe2,
  Headset,
  History,
  Info,
  LayoutDashboard,
  MessageSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  Package,
  PanelRight,
  Palette,
  Paperclip,
  PartyPopper,
  Pencil,
  Pin,
  Save,
  Smile,
  Tag,
  Tags,
  TrendingUp,
  Users,
  Warehouse,
  Building2,
  CreditCard,
  CalendarDays,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  Ban,
  RefreshCw,
  Facebook,
  Gift,
  Heart,
  Handshake,
  House,
  Image,
  ImagePlus,
  Instagram,
  Lock,
  LockKeyhole,
  LogOut,
  List,
  Map,
  MapPin,
  Mail,
  Maximize2,
  MessageCircle,
  MessagesSquare,
  Minus,
  Music2,
  Phone,
  Plus,
  RotateCcw,
  RotateCw,
  Settings,
  Search,
  Send,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  Sofa,
  Store,
  Sun,
  Table,
  Trash2,
  Truck,
  Upload,
  Utensils,
  UtensilsCrossed,
  Video,
  Wallet,
  Clock3,
  Youtube,
  User,
  X,
  Eye,
  EyeOff,
  Menu,
} from 'lucide-vue-next'

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  size: {
    type: Number,
    default: 16,
  },
  strokeWidth: {
    type: Number,
    default: 1.8,
  },
})

const iconMap = {
  alert: AlertTriangle,
  alignLeft: AlignLeft,
  armchair: Armchair,
  bed: Bed,
  bedDouble: BedDouble,
  bell: Bell,
  bot: Bot,
  briefcase: Briefcase,
  chartBar: BarChart3,
  checkCheck: CheckCheck,
  cloudUpload: CloudUpload,
  clipboardList: ClipboardList,
  crown: Crown,
  download: Download,
  edit: Pencil,
  filePlus: FilePlus,
  fileText: FileText,
  flag: Flag,
  fullscreen: Fullscreen,
  filter: Filter,
  globe: Globe2,
  headset: Headset,
  history: History,
  info: Info,
  layoutDashboard: LayoutDashboard,
  messageSquare: MessageSquare,
  messages: MessagesSquare,
  monitor: Monitor,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  panelRight: PanelRight,
  palette: Palette,
  paperclip: Paperclip,
  pencil: Pencil,
  pin: Pin,
  save: Save,
  smile: Smile,
  tag: Tag,
  category: Tags,
  trendingUp: TrendingUp,
  users: Users,
  userCircle: User,
  warehouse: Warehouse,
  badgePercent: BadgePercent,
  banknote: Banknote,
  cash: Banknote,
  building2: Building2,
  cart: ShoppingCart,
  creditCard: CreditCard,
  calendar: CalendarDays,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  'chevron-left': ChevronLeft,
  chevronRight: ChevronRight,
  'chevron-right': ChevronRight,
  ban: Ban,
  refresh: RefreshCw,
  clock: Clock3,
  clock3: Clock3,
  copy: Copy,
  user: User,
  list: List,
  map: Map,
  mapPin: MapPin,
  maximize: Maximize2,
  lock: Lock,
  mail: Mail,
  messageCircle: MessageCircle,
  messagesSquare: MessagesSquare,
  minus: Minus,
  music2: Music2,
  phone: Phone,
  plus: Plus,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  search: Search,
  send: Send,
  shield: Shield,
  sparkles: Sparkles,
  sofa: Sofa,
  box: Box,
  boxes: Boxes,
  axis3d: Axis3d,
  camera: Camera,
  heart: Heart,
  handshake: Handshake,
  house: House,
  image: Image,
  'image-plus': ImagePlus,
  eye: Eye,
  eyeOff: EyeOff,
  settings: Settings,
  gift: Gift,
  star: Star,
  sun: Sun,
  store: Store,
  table: Table,
  trash: Trash2,
  trash2: Trash2,
  truck: Truck,
  upload: Upload,
  utensils: Utensils,
  utensilsCrossed: UtensilsCrossed,
  video: Video,
  wallet: Wallet,
  cube: Boxes,
  logout: LogOut,
  close: X,
  x: X,
  check: Check,
  arrowLeft: ArrowLeft,
  home: House,
  lockKeyhole: LockKeyhole,
  package: Package,
  partyPopper: PartyPopper,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  menu: Menu,
  chevronUp: ChevronUp,
}

const iconComponent = computed(() => iconMap[props.name] ?? User)
</script>

<template>
  <component :is="iconComponent" :size="size" :stroke-width="strokeWidth" aria-hidden="true" />
</template>
