export const ROOM_TEMPLATES = [
  {
    id: 'bedroom',
    type: 'bedroom',
    name: 'Phòng ngủ',
    icon: 'bed',
    confidence: 94,
    suggestText: 'Gợi ý nội thất phù hợp với phòng ngủ phong cách ấm.',
    tags: ['Nordic', 'Tông ấm', 'Diện tích vừa'],
    isAvailable: true,
    statusText: 'Đã sẵn sàng để trực quan 3D.',
    modelUrl: '/src/features/room3d/models/rooms/tmp2ouvte8y_3d.gltf',
  },
  {
    id: 'living',
    type: 'living',
    name: 'Phòng khách',
    icon: 'sofa',
    confidence: 91,
    suggestText: 'Gợi ý sofa và bàn trà cho phòng khách hiện đại.',
    tags: ['Hiện đại', 'Sang trọng', 'Rộng rãi'],
    isAvailable: false,
    statusText: 'Phòng này đang được bổ sung mô hình 3D.',
    modelUrl: '/src/features/room3d/models/rooms/2_dense.glb',
  },
  {
    id: 'dining',
    type: 'dining',
    name: 'Phòng ăn',
    icon: 'utensilsCrossed',
    confidence: 89,
    suggestText: 'Gợi ý bộ bàn ăn và đèn thả trần cho khu ăn.',
    tags: ['Gia đình', 'Ấm cúng', 'Tối giản'],
    isAvailable: false,
    statusText: 'Phòng này đang được bổ sung mô hình 3D.',
    modelUrl: null,
  },
  {
    id: 'office',
    type: 'office',
    name: 'Phòng làm việc',
    icon: 'briefcase',
    confidence: 87,
    suggestText: 'Gợi ý bàn, ghế và kệ sách giúp tối ưu hiệu suất.',
    tags: ['Công năng', 'Tinh gọn', 'Chuyên nghiệp'],
    isAvailable: false,
    statusText: 'Phòng này đang được bổ sung mô hình 3D.',
    modelUrl: null,
  },
]

export const PRODUCTS_3D = [
  {
    id: 1,
    name: 'Ghế Ergonomic ProFlex',
    icon: 'armchair',
    price: 1200000,
    category: 'chair',
    roomTypes: ['office', 'bedroom'],
    modelUrl: '/src/features/room3d/models/furniture/chair.glb',
    fallback: { width: 0.6, height: 1, depth: 0.6, color: '#5a7a8a' },
  },
  {
    id: 2,
    name: 'Giường Agape',
    icon: 'bed',
    price: 5900000,
    category: 'bed',
    roomTypes: ['bedroom'],
    modelUrl: '/src/features/room3d/models/furniture/bed_agape.glb',
    fallback: { width: 1.9, height: 0.55, depth: 2.25, color: '#8b6e4e' },
  },
  {
    id: 7,
    name: 'Giường SoftSleep',
    icon: 'bedDouble',
    price: 6800000,
    category: 'bed',
    roomTypes: ['bedroom'],
    modelUrl: '/src/features/room3d/models/furniture/bed_agape.glb',
    fallback: { width: 2, height: 0.6, depth: 2.3, color: '#7c6652' },
  },
  {
    id: 3,
    name: 'Sofa Nordic 3 chỗ',
    icon: 'sofa',
    price: 8500000,
    category: 'sofa',
    roomTypes: ['living'],
    modelUrl: '/src/features/room3d/models/furniture/sofa-nordic.glb',
    fallback: { width: 2.1, height: 0.8, depth: 0.95, color: '#6a8080' },
  },
  {
    id: 4,
    name: 'Bàn ăn 6 ghế',
    icon: 'utensilsCrossed',
    price: 4500000,
    category: 'table',
    roomTypes: ['dining'],
    modelUrl: '/src/features/room3d/models/furniture/dining-table.glb',
    fallback: { width: 1.5, height: 0.75, depth: 0.9, color: '#8b6914' },
  },
  {
    id: 5,
    name: 'Bàn làm việc 1m4',
    icon: 'table',
    price: 1800000,
    category: 'table',
    roomTypes: ['office'],
    modelUrl: '/src/features/room3d/models/furniture/desk-140.glb',
    fallback: { width: 1.4, height: 0.75, depth: 0.7, color: '#6b4e2e' },
  },
  {
    id: 6,
    name: 'Kệ sách treo tường',
    icon: 'box',
    price: 680000,
    category: 'shelf',
    roomTypes: ['office', 'bedroom'],
    modelUrl: '/src/features/room3d/models/furniture/wall-shelf.glb',
    fallback: { width: 1.2, height: 0.3, depth: 0.3, color: '#7a7a7a' },
  },
]

export const PRODUCT_FILTERS = [
  { label: 'Tất cả', value: 'all' },
  { label: 'Ghế', value: 'chair' },
  { label: 'Giường', value: 'bed' },
  { label: 'Bàn', value: 'table' },
  { label: 'Sofa', value: 'sofa' },
]
