export const ROOM_TEMPLATES = [
  {
    id: 'bedroom',
    type: 'bedroom',
    name: 'Phong Ngu',
    emoji: '🛏️',
    confidence: 94,
    suggestText: 'Goi y noi that phu hop phong ngu phong cach am.',
    tags: ['Nordic', 'Tone am', 'Dien tich vua'],
    isAvailable: true,
    statusText: 'Da san sang truc quan 3D.',
    modelUrl: '/src/features/room3d/models/rooms/tmp2ouvte8y_3d.gltf',
  },
  {
    id: 'living',
    type: 'living',
    name: 'Phong Khach',
    emoji: '🛋️',
    confidence: 91,
    suggestText: 'Goi y sofa va ban tra cho phong khach hien dai.',
    tags: ['Hien dai', 'Sang trong', 'Rong rai'],
    isAvailable: false,
    statusText: 'Phong nay dang duoc bo sung model.',
    modelUrl: '/src/features/room3d/models/rooms/2_dense.glb',
  },
  {
    id: 'dining',
    type: 'dining',
    name: 'Phong An',
    emoji: '🍽️',
    confidence: 89,
    suggestText: 'Goi y bo ban an va den tha tran cho khu an.',
    tags: ['Gia dinh', 'Am cung', 'Toi gian'],
    isAvailable: false,
    statusText: 'Phong nay dang duoc bo sung model.',
    modelUrl: null,
  },
  {
    id: 'office',
    type: 'office',
    name: 'Phong Lam Viec',
    emoji: '💼',
    confidence: 87,
    suggestText: 'Goi y ban, ghe va ke sach toi uu hieu suat.',
    tags: ['Cong nang', 'Tinh gon', 'Chuyen nghiep'],
    isAvailable: false,
    statusText: 'Phong nay dang duoc bo sung model.',
    modelUrl: null,
  },
]

export const PRODUCTS_3D = [
  {
    id: 1,
    name: 'Ghe Ergonomic ProFlex',
    emoji: '🪑',
    price: 1200000,
    category: 'chair',
    roomTypes: ['office', 'bedroom'],
    modelUrl: '/src/features/room3d/models/furniture/chair.glb',
    fallback: { width: 0.6, height: 1, depth: 0.6, color: '#5a7a8a' },
  },
  {
    id: 2,
    name: 'Giuong Agape',
    emoji: '🛏️',
    price: 5900000,
    category: 'bed',
    roomTypes: ['bedroom'],
    modelUrl: '/src/features/room3d/models/furniture/bed_agape.glb',
    fallback: { width: 1.9, height: 0.55, depth: 2.25, color: '#8b6e4e' },
  },
  {
    id: 7,
    name: 'Giuong SoftSleep',
    emoji: '🛌',
    price: 6800000,
    category: 'bed',
    roomTypes: ['bedroom'],
    modelUrl: '/src/features/room3d/models/furniture/bed_agape.glb',
    fallback: { width: 2, height: 0.6, depth: 2.3, color: '#7c6652' },
  },
  {
    id: 3,
    name: 'Sofa Nordic 3 cho',
    emoji: '🛋️',
    price: 8500000,
    category: 'sofa',
    roomTypes: ['living'],
    modelUrl: '/src/features/room3d/models/furniture/sofa-nordic.glb',
    fallback: { width: 2.1, height: 0.8, depth: 0.95, color: '#6a8080' },
  },
  {
    id: 4,
    name: 'Ban An 6 ghe',
    emoji: '🍽️',
    price: 4500000,
    category: 'table',
    roomTypes: ['dining'],
    modelUrl: '/src/features/room3d/models/furniture/dining-table.glb',
    fallback: { width: 1.5, height: 0.75, depth: 0.9, color: '#8b6914' },
  },
  {
    id: 5,
    name: 'Ban Lam Viec 1m4',
    emoji: '🪵',
    price: 1800000,
    category: 'table',
    roomTypes: ['office'],
    modelUrl: '/src/features/room3d/models/furniture/desk-140.glb',
    fallback: { width: 1.4, height: 0.75, depth: 0.7, color: '#6b4e2e' },
  },
  {
    id: 6,
    name: 'Ke Sach Treo Tuong',
    emoji: '📚',
    price: 680000,
    category: 'shelf',
    roomTypes: ['office', 'bedroom'],
    modelUrl: '/src/features/room3d/models/furniture/wall-shelf.glb',
    fallback: { width: 1.2, height: 0.3, depth: 0.3, color: '#7a7a7a' },
  },
]

export const PRODUCT_FILTERS = [
  { label: 'Tất cả', value: 'all' },
  { label: 'Ghế', value: 'chair' },
  { label: 'Giuong', value: 'bed' },
  { label: 'Bàn', value: 'table' },
  { label: 'Sofa', value: 'sofa' },
]
